un <- read.table("pt.PT_test2.un.s100.0.txt")
hm <- read.table("pt.PT_test2.hm.s100.0.txt")
rc <- read.table("pt.PT_test2.un.hetcount")
ne_diff <- abs(un$V2-hm$V2)
A <- data.frame(ne_diff,rc$V4)
B <- A[A$rc.V4>0,]
pdf("Figure_2.pdf")
reg <- lm(B$rc.V4~B$ne_diff)
coeff <- coefficients(reg)
eq <- paste0("y = ", round(coeff[2],1), " x ", round(coeff[1],1))
ken <- cor.test(B$rc.V4,B$ne_diff,method="kendall")
tau <- paste0("Tau = ",round(ken$estimate,3))
pval <- paste0("P-value = ", round(ken$p.value,3))
plot(B$rc.V4~B$ne_diff,xlab="Absolute difference in Ne Estimate",ylab="Repeat Content in %",pch=20)
abline(reg, col="blue",lwd=2,lty=4)
text(min(B$ne_diff)+0.5,0.2*max(B$rc.V4) + 4, labels=eq, srt=0.2, col = "red")
text(min(B$ne_diff)+0.5,0.2*max(B$rc.V4) + 7, labels=tau, col = "red")
text(min(B$ne_diff)+0.5,0.2*max(B$rc.V4) + 10, labels=pval, col = "red")
dev.off()

